Diplom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

cart/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', product_list, name='product_list'),
    path('catalog/<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', product_detail, name='product_detail'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.logouts, name='logouts'),
    path('register/', views.register, name='register'),
    path('edit_profile/', views.edit, name='edit'),
    path('personal_data/', views.personal_data, name='personal_data'),
]

templates/templates_shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="shortcut icon" href={% static 'image/favicon.ico' %}>
</head>
<body>
<header>
    <div class="logo">
        <a href="/">
            <img src={% static 'image/logo_store.png' %} width="60" height="60px" alt=""/>
        </a>
    </div>
    <div class="menu">
        <ul>
            <li><a href="/">Каталог</a></li>
            <li><a href="/">Контакты</a></li>
        </ul>
    </div>
    <div class="tel">
        <p>+375297426635</p>
    </div>
</header>
<div class="cart">
    {% if request.user.is_authenticated %}
        <a class="btn mb-4" href={% url 'users:personal_data' %}>Профиль</a>
        <a class="btn mb-4" href={% url 'users:logouts' %}>Выйти</a>
    {% else %}
        <a class="btn mb-4" href={% url 'users:register' %}>Регистрация</a>
        <a class="btn mb-4" href={% url 'users:login' %}>Войти</a>
    {% endif %}
</div>
<div class="cart">
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            Ваша корзина:
            {% if request.user.is_authenticated %}
                <a href="{% url "cart:cart_detail" %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
                </a>
            {% else %}
            <a href="{% url "users:login" %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
            </a>
            {% endif %}
        {% else %}
            Ваша корзина пуста.
        {% endif %}
    {% endwith %}
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<footer>&copy; Z31-Online Кучко Никита Алексеевич</footer>
</body>
</html>

templates/templates_shop/paginator.html
<div class="pagination">
        <span class="step-links">
            {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}">Previous</a>
            {% endif %}
            <span class="current">
                Page {{ page.number }} of {{ page.paginator.num_pages }}.
            </span>
            {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
            {% endif %}
        </span>
</div>

templates/templates_shop/product_detail.html
{% extends "templates_shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ product.title }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "/image/no-image-icon.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">

        </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

templates/templates_shop/product_list.html
{% extends "templates_shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">Все</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Все товары{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "image/no-image-icon.png" %}{% endif %}" alt="" width="150" height="150">
                </a>
                <br>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                {{ product.price }}$
            </div>
        {% endfor %}
    </div>
    {% include "templates_shop/paginator.html" with page=posts %}
{% endblock %}